---
- name: Nginx | Remove default nginx site
  notify: Reload nginx
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Nginx | Ensure sites-enabled exists
  file: path=/etc/nginx/sites-enabled state=directory

- name: Nginx | Install nginx configuration file
  notify: Reload nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf