---
- name: Check add-apt-repository
  apt: pkg=python-software-properties state=latest update_cache=yes cache_valid_time=3600

- name: Update repositories
  apt_repository: >
    repo={{ item }}
    state=present
    update_cache=yes
  with_items:
    - ppa:ansible/ansible

- name: Install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - ansible