---
- name: Create Sentry Database User
  sudo: True
  sudo_user: postgres
  postgresql_user: >
    user={{sentry_database_user}}
    password={{sentry_database_password}}
    role_attr_flags=NOCREATEDB,NOSUPERUSER

- name: Create Sentry Database
  sudo: True
  sudo_user: postgres
  postgresql_db: >
    name={{sentry_database_name}}
    owner={{sentry_database_user}}
    template=template0
    encoding='{{sentry_encoding}}'
    lc_collate='{{sentry_collate}}'
    lc_ctype='{{sentry_ctype}}'