---
- name: Commmon | Install required system packages.
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
    cache_valid_time=3600
  with_items:
    - redis-server

- name: Start redis
  service: name=redis-server state=started enabled=yes