---
- name: Create Database User
  sudo_user: postgres
  sudo: True
  postgresql_user: >
    user={{teamcity_database_user}}
    password={{teamcity_database_password}}
    role_attr_flags=NOCREATEDB,NOSUPERUSER

- name: Create Database
  sudo_user: postgres
  sudo: True
  postgresql_db: >
    name={{teamcity_database_name}}
    owner={{teamcity_database_user}}
    template=template0
    encoding='{{teamcity_encoding}}'
    lc_collate='{{teamcity_collate}}'
    lc_ctype='{{teamcity_ctype}}'