- name: Make Nginx SSL directory
  file: dest='/etc/nginx/ssl/' state=directory

- name: Copy Nginx SSL
  copy: src={{item}} dest=/etc/nginx/ssl/{{item}} owner=www-data group=www-data mode=0400
  register: certs
  with_items:
    - pypiserver.crt
    - pypiserver.key.pass

- name: Strip ssl key
  when: certs|changed
  command: openssl rsa -in /etc/nginx/ssl/pypiserver.key.pass -out /etc/nginx/ssl/pypiserver.key -passin pass:{{pypiserver_ssl_passphrase}}
  notify: Reload nginx

- name: Fix ssl key owner
  when: certs|changed
  file: path=/etc/nginx/ssl/pypiserver.key owner=www-data group=www-data mode=0400