---
- include: users.yml tags=users,pypiserver
- include: packages.yml tags=packages,pypiserver
- include: upstart.yml tags=upstart,pypiserver
- include: config.yml tags=config,pypiserver
- include: assets.yml tags=assets,pypiserver
- include: vhost.yml tags=vhost,pypiserver