---
- name: Check add-apt-repository
  apt: pkg=python-software-properties state=latest update_cache=yes cache_valid_time=3600

- name: Add apt key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present

- name: Add apt repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_lsb.codename}}-pgdg main {{postgres_version}}'

- name: Install pgdg-key
  apt: pkg=pgdg-keyring state=latest update_cache=yes

- name: Install packages
  apt: >
    pkg={{item}}
    state=latest
  with_items:
    - postgresql-{{postgres_version}}
    - postgresql-client-{{postgres_version}}
    - postgresql-contrib-{{postgres_version}}
    - python-psycopg2

- name: Start postgresql
  service: name=postgresql state=started enabled=yes